#!/usr/bin/env python
# -*- coding: utf-8 -*-

import locale

#NOTE: This list has been optimized for Sailfish OS and the characters available there.
currencies = {
    'AED': ['د.إ', 2],
    'AFN': ['؋', 2],
    'ALL': ['L', 2],
    'ANG': ['ƒ', 2],
    'AMD': ['d.', 2],
    'AOA': ['Kz', 2],
    'ARS': ['$', 2],
    'AUD': ['$', 2],
    'AWG': ['ƒ', 2],
    'AZN': ['A.M.', 2],
    'BAM': ['KM', 2],
    'BBD': ['$', 2],
    'BDT': ['Tk.', 2],
    'BGN': ['лв', 2],
    'BHD': ['.د.ب', 3],
    'BIF': ['Fr', 2],
    'BMD': ['$', 2],
    'BND': ['$', 2],
    'BOB': ['Bs.', 2],
    'BRL': ['R$', 2],
    'BSD': ['$', 2],
    'BTN': ['Nu.', 2],
    'BWP': ['P', 2],
    'BYR': ['Br', 2],
    'BZD': ['$', 2],
    'CAD': ['$', 2],
    'CDF': ['Fr', 2],
    'CHF': ['Fr', 2],
    'CLP': ['$', 2],
    'CNY': ['¥', 2],
    'COP': ['$', 2],
    'CRC': ['₡', 2],
    'CUC': ['$', 2],
    'CUP': ['$', 2],
    'CVE': ['Esc', 2],
    'CZK': ['Kč', 2],
    'DJF': ['Fr', 2],
    'DKK': ['kr', 2],
    'DOP': ['$', 2],
    'DZD': ['د.ج', 2],
    'EGP': ['£', 2],
    'ERN': ['Nfk', 2],
    'ETB': ['Br', 2],
    'EUR': ['€', 2],
    'FJD': ['$', 2],
    'FKP': ['£', 2],
    'GBP': ['£', 2],
    'GGP': ['£', 2],
    'GHS': ['₵', 2],
    'GIP': ['£', 2],
    'GMD': ['D', 2],
    'GNF': ['Fr', 2],
    'GTQ': ['Q', 2],
    'GYD': ['$', 2],
    'HKD': ['$', 2],
    'HNL': ['L', 2],
    'HRK': ['kn', 2],
    'HTG': ['G', 2],
    'HUF': ['Ft', 2],
    'IDR': ['Rp', 2],
    'ILS': ['NIS', 2],
    'IMP': ['£', 2],
    'INR': ['₹', 2],
    'IQD': ['ع.د', 3],
    'IRR': ['﷼', 2],
    'ISK': ['kr', 2],
    'JEP': ['£', 2],
    'JMD': ['$', 2],
    'JOD': ['د.ا', 2],
    'JPY': ['¥', 2],
    'KES': ['Sh', 2],
    'KGS': ['лв', 2],
    'KHR': ['CR', 2],
    'KMF': ['Fr', 2],
    'KPW': ['₩', 2],
    'KWD': ['د.ك', 3],
    'KYD': ['$', 2],
    'LBP': ['ل.ل', 2],
    'LKR': ['Rs', 2],
    'LRD': ['$', 2],
    'LSL': ['L', 2],
    'LYD': ['ل.د', 3],
    'MAD': ['د.م.', 2],
    'MDL': ['L', 2],
    'MGA': ['Ar', 1],
    'MKD': ['ден', 2],
    'MMK': ['Ks', 2],
    'MOP': ['P', 2],
    'MRO': ['UM', 1],
    'MUR': ['Rs', 2],
    'MVR': ['Rf', 2],
    'MWK': ['MK', 2],
    'MXN': ['$', 2],
    'MYR': ['RM', 2],
    'MZN': ['MT', 2],
    'NAD': ['$', 2],
    'NGN': ['₦', 2],
    'NIO': ['C$', 2],
    'NOK': ['kr', 2],
    'NPR': ['NRs', 2],
    'NZD': ['$', 2],
    'OMR': ['ر.ع.', 3],
    'PAB': ['B/.', 2],
    'PEN': ['S/.', 2],
    'PGK': ['K', 2],
    'PHP': ['₱', 2],
    'PKR': ['Rs.', 2],
    'PLN': ['zł', 2],
    'PRB': ['р.', 2],
    'PYG': ['₲', 2],
    'QAR': ['ر.ق', 2],
    'RON': ['lei', 2],
    'RSD': ['дин.', 2],
    'RUB': ['руб.', 2],
    'RWF': ['Fr', 2],
    'SAR': ['ر.س', 2],
    'SBD': ['$', 2],
    'SCR': ['SR', 2],
    'SDG': ['£', 2],
    'SEK': ['kr', 2],
    'SGD': ['$', 2],
    'SHP': ['£', 2],
    'SLL': ['Le', 2],
    'SOS': ['Sh', 2],
    'SRD': ['$', 2],
    'SSP': ['£', 2],
    'STD': ['Db', 2],
    'SYP': ['£', 2],
    'SZL': ['L', 2],
    'THB': ['฿', 2],
    'TJS': ['ЅМ', 2],
    'TMT': ['m', 2],
    'TND': ['د.ت', 3],
    'TOP': ['T$', 2],
    'TRY': ['₺', 2],
    'TTD': ['$', 2],
    'TWD': ['$', 2],
    'TZS': ['Sh', 2],
    'UAH': ['грн', 2],
    'UGX': ['Sh', 2],
    'USD': ['$', 2],
    'UYU': ['$', 2],
    'UZS': ['лв', 2],
    'VEF': ['Bs', 2],
    'VND': ['₫', 1],
    'VUV': ['Vt', 0],
    'WST': ['T', 2],
    'XAF': ['Fr', 2],
    'XCD': ['$', 2],
    'XOF': ['Fr', 2],
    'XPF': ['Fr', 2],
    'YER': ['﷼', 2],
    'ZAR': ['R', 2],
    'ZMW': ['ZK', 2]}

def format_currency(value, currency):
    global currencies
    try:
        symbol, sub = currencies[currency]
    except KeyError:
        symbol, sub = currency, 2
    if value == int(value):
        return symbol + ' ' + str(value)
    locale.resetlocale()
    decimal = locale.localeconv()['mon_decimal_point']
    if decimal == '':
        decimal = locale.localeconv()['decimal_point']
    if decimal == '':
        decimal = '.'
    predec = int(value)
    postdec = abs(int(round(value - predec, sub) * (10 ** sub)))
    return symbol + ' ' + str(predec) + decimal + str(postdec)
